{"issue":{"id":745,"project":{"id":16,"name":"easySDI"},"tracker":{"id":1,"name":"Defect"},"status":{"id":6,"name":"Rejected"},"priority":{"id":4,"name":"Normal"},"author":{"id":383,"name":"Blatti Yves"},"category":{"id":12,"name":"CORE"},"subject":"Unable to update from 4.1.0 to 4.2.0 Beta-1","description":"Unable to update from 4.1.0 to 4.2.0 Beta-1\r\nMessage at installation:\r\n\r\n<pre>\r\nCannot add or update a child row: a foreign key constraint fails (`dev`., CONSTRAINT `jos_sdi_order_fk4` FOREIGN KEY (`thirdparty_id`) REFERENCES `jos_sdi_organism` (`id`) ON DELETE NO ACTION ON UPDATE NO ACT) \r\n\r\nSQL=ALTER TABLE `jos_sdi_order` ADD CONSTRAINT `jos_sdi_order_fk4` FOREIGN KEY (`thirdparty_id`) REFERENCES `jos_sdi_organism` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;\r\n</pre> ","done_ratio":0,"custom_fields":[{"id":2,"name":"Affected version","value":"150"}],"created_on":"2014-06-17T12:22:04Z","updated_on":"2015-09-18T15:23:49Z","closed_on":"2014-06-23T06:52:59Z","journals":[{"id":3509,"user":{"id":383,"name":"Blatti Yves"},"notes":"My bad:\r\nError comes from my migrated data (In v2, an order without third party was set with an id of \"0\", now it's set to null).\r\nThis issue can be rejected, sorry about that.","created_on":"2014-06-18T08:58:50Z","details":[]},{"id":3510,"user":{"id":9,"name":"M\u00e9rour Xavier"},"notes":"Please reject it Bruno","created_on":"2014-06-18T16:39:25Z","details":[{"property":"attr","name":"assigned_to_id","new_value":"3"}]},{"id":3514,"user":{"id":3,"name":"Magoni Bruno"},"notes":"","created_on":"2014-06-23T06:52:59Z","details":[{"property":"attr","name":"status_id","old_value":"1","new_value":"6"},{"property":"attr","name":"assigned_to_id","old_value":"3","new_value":"383"}]},{"id":6499,"user":{"id":23,"name":"Van Hoecke H\u00e9l\u00e8ne "},"created_on":"2015-09-18T15:23:49Z","details":[{"property":"attr","name":"assigned_to_id","old_value":"383"}]}]}}