{"issue":{"id":865,"project":{"id":16,"name":"easySDI"},"tracker":{"id":1,"name":"Defect"},"status":{"id":10,"name":"Closed"},"priority":{"id":5,"name":"High"},"author":{"id":383,"name":"Blatti Yves"},"category":{"id":17,"name":"CATALOG"},"subject":"Unable to save a catalog ","description":"Unable to save a catalog:\r\n<pre>\r\nUnknown column 'created' in 'field list' SQL=INSERT INTO `jos_sdi_catalog_resourcetype` (`ordering`,`state`,`catalog_id`,`resourcetype_id`,`created`,`created_by`,`guid`) VALUES ('2','1','2','2','2014-11-18 13:19:31','10000','ad3bcbbc-ec0e-ae04-c508-bcf16a899e3b') \r\n</pre>\r\n\r\nIt seems to be a change introduced in: \"7529\":https://forge.easysdi.org/projects/easysdi/repository/revisions/7529/diff/branches/4.2.x/joomla/easysdi/com_easysdi_catalog/src/administrator/tables/catalogresourcetype.php\r\n\r\n*Easysdi_catalogTablecatalogresourcetype* now extends *sdiTable* (previously : JTable) but database model doesn't fit (no _created_, _modified_, _..._by_ ... fields)","start_date":"2014-11-18","done_ratio":0,"custom_fields":[{"id":2,"name":"Affected version","value":"158"}],"created_on":"2014-11-18T13:25:44Z","updated_on":"2015-09-18T15:22:43Z","closed_on":"2015-02-11T16:58:24Z","journals":[{"id":4345,"user":{"id":383,"name":"Blatti Yves"},"notes":"","created_on":"2014-11-18T13:26:19Z","details":[{"property":"attr","name":"description","old_value":"Unable to save a catalog:\r\n<pre>\r\nUnknown column 'created' in 'field list' SQL=INSERT INTO `jos_sdi_catalog_resourcetype` (`ordering`,`state`,`catalog_id`,`resourcetype_id`,`created`,`created_by`,`guid`) VALUES ('2','1','2','2','2014-11-18 13:19:31','10000','ad3bcbbc-ec0e-ae04-c508-bcf16a899e3b') \r\n</pre>\r\n\r\nIt seems to be a change introduced in: \"7529\":https://forge.easysdi.org/projects/easysdi/repository/revisions//diff/branches/4.2.x/joomla/easysdi/com_easysdi_catalog/src/administrator/tables/catalogresourcetype.php\r\n\r\n*Easysdi_catalogTablecatalogresourcetype* now extends *sdiTable* but database model doesn't fit (no _created_, _modified_, _..._by_ ... fields)","new_value":"Unable to save a catalog:\r\n<pre>\r\nUnknown column 'created' in 'field list' SQL=INSERT INTO `jos_sdi_catalog_resourcetype` (`ordering`,`state`,`catalog_id`,`resourcetype_id`,`created`,`created_by`,`guid`) VALUES ('2','1','2','2','2014-11-18 13:19:31','10000','ad3bcbbc-ec0e-ae04-c508-bcf16a899e3b') \r\n</pre>\r\n\r\nIt seems to be a change introduced in: \"7529\":https://forge.easysdi.org/projects/easysdi/repository/revisions//diff/branches/4.2.x/joomla/easysdi/com_easysdi_catalog/src/administrator/tables/catalogresourcetype.php\r\n\r\n*Easysdi_catalogTablecatalogresourcetype* now extends *sdiTable* (previously : JTable) but database model doesn't fit (no _created_, _modified_, _..._by_ ... fields)"}]},{"id":4346,"user":{"id":383,"name":"Blatti Yves"},"notes":"","created_on":"2014-11-18T13:28:04Z","details":[{"property":"attr","name":"description","old_value":"Unable to save a catalog:\r\n<pre>\r\nUnknown column 'created' in 'field list' SQL=INSERT INTO `jos_sdi_catalog_resourcetype` (`ordering`,`state`,`catalog_id`,`resourcetype_id`,`created`,`created_by`,`guid`) VALUES ('2','1','2','2','2014-11-18 13:19:31','10000','ad3bcbbc-ec0e-ae04-c508-bcf16a899e3b') \r\n</pre>\r\n\r\nIt seems to be a change introduced in: \"7529\":https://forge.easysdi.org/projects/easysdi/repository/revisions//diff/branches/4.2.x/joomla/easysdi/com_easysdi_catalog/src/administrator/tables/catalogresourcetype.php\r\n\r\n*Easysdi_catalogTablecatalogresourcetype* now extends *sdiTable* (previously : JTable) but database model doesn't fit (no _created_, _modified_, _..._by_ ... fields)","new_value":"Unable to save a catalog:\r\n<pre>\r\nUnknown column 'created' in 'field list' SQL=INSERT INTO `jos_sdi_catalog_resourcetype` (`ordering`,`state`,`catalog_id`,`resourcetype_id`,`created`,`created_by`,`guid`) VALUES ('2','1','2','2','2014-11-18 13:19:31','10000','ad3bcbbc-ec0e-ae04-c508-bcf16a899e3b') \r\n</pre>\r\n\r\nIt seems to be a change introduced in: \"7529\":https://forge.easysdi.org/projects/easysdi/repository/revisions/7529/diff/branches/4.2.x/joomla/easysdi/com_easysdi_catalog/src/administrator/tables/catalogresourcetype.php\r\n\r\n*Easysdi_catalogTablecatalogresourcetype* now extends *sdiTable* (previously : JTable) but database model doesn't fit (no _created_, _modified_, _..._by_ ... fields)"}]},{"id":4679,"user":{"id":787,"name":"Villemagne J\u00e9r\u00f4me"},"notes":"Hello Yves,\r\n\r\nit was fixed in 4.2.x and thus should be fix in 4.3.x ; if you're agree, you can close it :-)","created_on":"2015-01-21T07:29:46Z","details":[{"property":"attr","name":"status_id","old_value":"1","new_value":"2"},{"property":"attr","name":"assigned_to_id","new_value":"383"}]},{"id":4682,"user":{"id":383,"name":"Blatti Yves"},"notes":"Perfect, thanks","created_on":"2015-02-11T10:18:31Z","details":[{"property":"attr","name":"assigned_to_id","old_value":"383","new_value":"787"}]},{"id":4686,"user":{"id":787,"name":"Villemagne J\u00e9r\u00f4me"},"notes":"","created_on":"2015-02-11T16:58:15Z","details":[{"property":"attr","name":"status_id","old_value":"2","new_value":"3"}]},{"id":4687,"user":{"id":787,"name":"Villemagne J\u00e9r\u00f4me"},"notes":"","created_on":"2015-02-11T16:58:24Z","details":[{"property":"attr","name":"status_id","old_value":"3","new_value":"10"}]},{"id":6450,"user":{"id":23,"name":"Van Hoecke H\u00e9l\u00e8ne "},"created_on":"2015-09-18T15:22:43Z","details":[{"property":"attr","name":"assigned_to_id","old_value":"787"}]}]}}